package com.rush.cloud.betslip.request;

import java.util.List;

import com.rush.cloud.betslip.common.Badge;
import com.rush.cloud.betslip.common.Platform;
import com.rush.cloud.betslip.common.PlayType;

import io.quarkus.runtime.annotations.RegisterForReflection;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@RegisterForReflection
public class BetSlipImageGenerationRequest {

    private Platform platform;
    private PlayType playType;
    private List<Badge> badges;
    private HeaderContent header;
    private List<Selection> selections;
    private FooterContent footer;

    @Data
    @RegisterForReflection
    public static class Selection {

        private String label;  // $.outcomes.label
        private String odds;   // $couponRows.playedOdds
        private String oddsBoosted;   // $couponRows.betOddsBoosted
        private String bettingMarketType;  // $.betOffers.criterion
        private String eventName;   // $.events.eventName
        private String eventStartDate;  // $events.eventStartDate
    }

    @Data
    @RegisterForReflection
    public static class HeaderContent {

        private String myBetsText;  // static
        private String betTitle;  // generated by the client based on the fingerprint
        private String totalOdds;  // $.bets.playedOdds (needs to be converted based on player odds format)
        private String descriptionLeft;  // $.events.eventName (only applicable for SGP)
        private String descriptionRight; // $events.eventStartDate (only applicable for SGP)
        private String lineDescription; // generated by the client (only applicable for Multiple SGP)
    }

    @Data
    @RegisterForReflection
    public static class FooterContent {
        private String totalWagerText;  // static
        private String totalWagerAmount;  // sum of $.bets.stake
        private String potentialPayoutText;  // static
        private String potentialPayoutAmount; // TODO sum of $.bets.potentialPayout. $.bets.potentialPayoutBoosted if rewardType=PROFIT_BOOST - can be different from the one Kambi showed in their betslip
        private String potentialPayoutAmountBoosted;
        private String gamblingProblemLine1;  // static
        private String gamblingProblemLine2;  // static
        private String betDateTime;  // $.placedDate
    }
}