name: Update lambda
on:
  push:
    branches:
      - main
jobs:
  build-native-and-update-lambda:
    runs-on: ubuntu-latest
    env:
      OS: linux
    steps:
      - uses: actions/checkout@v2
      - name: Install graalvm
        uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '22.1.0.java11'
      - name: Install native-image
        run: gu install native-image
      - name: Build native executable
        run: ./gradlew build -Dquarkus.package.type=native
      - name: Update AWS lambda with native executable
        run: bash build/manage.sh native create
        env:
          LAMBDA_ROLE_ARN: arn:aws:iam::256683732175:role/lambda-ex
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}