name: Update lambda
on:
  push:
    branches:
      - main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      OS: linux
    steps:
      - uses: actions/checkout@v2
      - name: Install graalvm
        uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm: '22.1.0'
          java: 'java11'
      - name: Install native-image
        run: gu install native-image
      - name: Build native executable
        run: ./gradlew build -Dquarkus.package.type=native
      - name: Update AWS lambda with native executable
        run: sh build/manage.sh native update
        env:
          LAMBDA_ROLE_ARN: arn:aws:iam::256683732175:role/lambda-ex